# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f \u043f\u0438\u0441\u0430\u0442\u0435\u043b\u044f')),
                ('century', models.IntegerField(verbose_name='\u0412\u0435\u043a')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='/img/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
