# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapgeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobjects',
            name='century',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='\u0412\u0435\u043a'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='geom',
            field=djgeojson.fields.PointField(verbose_name='\u041c\u0435\u0441\u0442\u043e \u043d\u0430 \u043a\u0430\u0440\u0442\u0435'),
        ),
        migrations.AlterField(
            model_name='mapobjects',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
