# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapgeo', '0002_auto_20160329_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField(verbose_name='\u041c\u0435\u0441\u0442\u043e \u043d\u0430 \u043a\u0430\u0440\u0442\u0435')),
            ],
        ),
        migrations.RemoveField(
            model_name='mapobjects',
            name='geom',
        ),
    ]
