# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:56
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapgeo', '0003_auto_20160331_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapPoint',
        ),
        migrations.AddField(
            model_name='mapobjects',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043d\u0430 \u043a\u0430\u0440\u0442\u0435'),
        ),
    ]
